version: '3.9'

services:
#   api:
#     ... 
  web:
    image: ghcr.io/ntdesmond/gunicorn-nginx-proxy:latest
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
    ports:
    - "80:80"
    environment:
      TARGET_HOSTNAME: api
